# generate-collector-env.ps1
# Reads .env, computes the Langfuse Base64 auth header, and writes collector.env.
# Run this AFTER editing .env, then restart the collector.
#
# Usage:
#   cd d:\Observation_Layer
#   .\infrastructure\generate-collector-env.ps1
#   docker compose restart otel-collector

param(
    [string]$EnvFile = ".env",
    [string]$OutputFile = "infrastructure/collector.env"
)

$ErrorActionPreference = "Stop"

if (-not (Test-Path $EnvFile)) {
    Write-Host "ERROR: $EnvFile not found. Run this from the repo root." -ForegroundColor Red
    exit 1
}

# Parse .env into a hashtable
$envVars = @{}
Get-Content $EnvFile | ForEach-Object {
    $line = $_.Trim()
    if ($line -and -not $line.StartsWith("#")) {
        $parts = $line -split '=', 2
        if ($parts.Length -eq 2) {
            $key = $parts[0].Trim()
            $val = $parts[1].Trim('"').Trim("'")
            $envVars[$key] = $val
        }
    }
}

# Required keys
$required = @("LANGFUSE_PUBLIC_KEY", "LANGFUSE_SECRET_KEY", "LANGSMITH_API_KEY", "LANGSMITH_PROJECT")
foreach ($k in $required) {
    if (-not $envVars.ContainsKey($k) -or $envVars[$k] -match "your_|xxxx") {
        Write-Host "ERROR: $k is missing or has a placeholder value in $EnvFile" -ForegroundColor Red
        exit 1
    }
}

# Generate the Langfuse Base64 auth header from public:secret
$pub = $envVars["LANGFUSE_PUBLIC_KEY"]
$sec = $envVars["LANGFUSE_SECRET_KEY"]
$raw = "$($pub):$($sec)"
$authHeader = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($raw))

# Determine the Langfuse host for the Docker network
# When running inside Docker, the collector reaches Langfuse via the container hostname
$langfuseHost = "http://langfuse-web:3000"

# Determine Phoenix endpoint (internal Docker network)
$phoenixEndpoint = "phoenix:4317"

# LangSmith endpoint (SaaS)
$langsmithEndpoint = "https://api.smith.langchain.com/otel"

# Write collector.env
$content = @"
# AUTO-GENERATED by generate-collector-env.ps1 — do NOT edit manually.
# To change keys, edit .env then re-run: .\infrastructure\generate-collector-env.ps1

# Langfuse (self-hosted, inside Docker network)
LANGFUSE_HOST=$langfuseHost
LANGFUSE_AUTH_HEADER=$authHeader

# Arize Phoenix (self-hosted, inside Docker network)
PHOENIX_ENDPOINT=$phoenixEndpoint

# LangSmith (SaaS, over HTTPS)
LANGSMITH_OTLP_ENDPOINT=$langsmithEndpoint
LANGSMITH_API_KEY=$($envVars["LANGSMITH_API_KEY"])
LANGSMITH_PROJECT=$($envVars["LANGSMITH_PROJECT"])
"@

$content | Set-Content -Path $OutputFile -Encoding UTF8 -NoNewline

Write-Host ""
Write-Host "  collector.env generated successfully!" -ForegroundColor Green
Write-Host ""
Write-Host "  Langfuse public key:  $pub" -ForegroundColor Cyan
Write-Host "  Auth header:           $($authHeader.Substring(0,20))..." -ForegroundColor Cyan
Write-Host "  LangSmith project:     $($envVars['LANGSMITH_PROJECT'])" -ForegroundColor Cyan
Write-Host ""
Write-Host "  Written to: $OutputFile" -ForegroundColor Green
Write-Host ""
Write-Host "  Next step: restart the collector" -ForegroundColor Yellow
Write-Host "    docker compose restart otel-collector" -ForegroundColor Yellow
Write-Host ""